name: Run CI

on:
  push:
    branches: 
      - develop
      - issue/github-action
  pull_request:
    branches:
      - develop
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        php: [ '7.2', '7.3', '7.4' ]
        wp: [ 'latest' ]
        include:
          - php: '7.4'
            env:
              WP_VERSION: master
              WP_ALLOW_MULTISITE: 1
    name: PHP ${{ matrix.php }} WP ${{ matrix.wp }}
    timeout-minutes: 15
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.wp == 'nightly' }}
    services:
      database:
        image: mysql:5.6
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer
          extensions: mysql
          coverage: none

      - name: Tool versions
        run: |
          php --version
          composer --version
          
      - name: Get cached composer directories
        uses: actions/cache@v2
        with:
          path: |
            ./packages
            ./vendor
          key: ${{ runner.os }}-${{ hashFiles('./composer.lock') }}
          
      - name: Setup composer
        run: composer install
        
      - name: Init DB and WP
        run: ./tests/bin/install.sh as_test root root 127.0.0.1 ${{ matrix.wp }}

      - name: Run tests
        run: ./vendor/bin/phpunit -c ./phpunit.xml